# Generated by Django 2.2.19 on 2021-07-23 20:15

from django.db import migrations, models
import education.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_de_l_etablissement', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('nom_etablissement', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('type_etablissement', models.CharField(blank=True, choices=[('Défaut', 'DEFAUT'), ('Autre', 'AUTRE'), ('Ecole', 'ECOLE'), ('Collège', 'COLLEGE'), ('Lycée', 'LYCEE'), ('Service Administratif', 'ADMIN'), ('Information et orientation', 'INFO')], default=education.models.TypeEtabEnum('Défaut'), max_length=128, null=True)),
                ('status_public_prive', models.CharField(blank=True, choices=[('Défaut', 'DEFAUT'), ('Autre', 'AUTRE'), ('Public', 'PUBLIC'), ('Privé', 'PRIVE')], default=education.models.StatusEnum('Défaut'), max_length=128, null=True)),
                ('etat', models.CharField(blank=True, choices=[('Défaut', 'DEFAUT'), ('Autre', 'AUTRE'), ('Ouvert', 'OUVERT'), ('Fermé', 'FERME')], default=education.models.EtatEnum('Défaut'), max_length=128, null=True)),
                ('ecole_maternelle', models.BooleanField(blank=True, default=False, null=True)),
                ('ecole_elementaire', models.BooleanField(blank=True, default=False, null=True)),
                ('voie_generale', models.BooleanField(blank=True, default=False, null=True)),
                ('voie_technologique', models.BooleanField(blank=True, default=False, null=True)),
                ('voie_professionnelle', models.BooleanField(blank=True, default=False, null=True)),
                ('fax', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('web', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('mail', models.EmailField(blank=True, default='', max_length=64, null=True)),
                ('adresse_1', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('adresse_2', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('adresse_3', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('code_postal', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('code_commune', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('nom_commune', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('restauration', models.BooleanField(blank=True, default=False, null=True)),
                ('hebergement', models.BooleanField(blank=True, default=False, null=True)),
                ('ulis', models.BooleanField(blank=True, default=False, null=True)),
                ('apprentissage', models.BooleanField(blank=True, default=False, null=True)),
                ('segpa', models.BooleanField(blank=True, default=False, null=True)),
                ('section_arts', models.BooleanField(blank=True, default=False, null=True)),
                ('section_cinema', models.BooleanField(blank=True, default=False, null=True)),
                ('section_theatre', models.BooleanField(blank=True, default=False, null=True)),
                ('section_sport', models.BooleanField(blank=True, default=False, null=True)),
                ('section_internationale', models.BooleanField(blank=True, default=False, null=True)),
                ('section_europeenne', models.BooleanField(blank=True, default=False, null=True)),
                ('lycee_agricole', models.BooleanField(blank=True, default=False, null=True)),
                ('lycee_militaire', models.BooleanField(blank=True, default=False, null=True)),
                ('lycee_des_metiers', models.BooleanField(blank=True, default=False, null=True)),
                ('post_bac', models.BooleanField(blank=True, default=False, null=True)),
                ('appartenance_education_prioritaire', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('siren_siret', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('fiche_onisep', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('nombre_d_eleves', models.IntegerField(blank=True, default=0, null=True)),
                ('date_ouverture', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('date_maj_ligne', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('type_contrat_prive', models.CharField(blank=True, choices=[('Défaut', 'DEFAUT'), ('Autre', 'AUTRE'), ('Sans Objet', 'SANS_OBJET'), ('Hors Contrat', 'HORS_CONTRAT'), ("Contrat d'Association Toutes Classes", 'CONTRAT_ASSO_TTS_CLASSES'), ("Contrat d'Association Parties des Classes", 'CONTRAT_ASSO_PART_CLASSES'), ('Contrat Simple Toutes Classes', 'CONTRAT_SIMPLE_TTS_CLASSES'), ('Contrat Simple Partie des Classes', 'CONTRAT_SIMPLE_PART_CLASSES')], default=education.models.TypeContratPriveEnum('Défaut'), max_length=64, null=True)),
            ],
        ),
    ]
